### ISSUE TITLE
Re-organize code templates

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/ml_code_generator#74]
Our project root directory has pandas_code/code_templates sub-directory. The code_templates sub-directory contains a variety of small snippets of code used to construct ML programs. We need to reorganize these snippets (templates) based on the libraries they are using. The proposed new structure is:

code_templates at the root directory
-- pandas
-- tensorflow
-- sklearn

Different code templates (.py files) should be moved to the appropriate sub-directory, based on the library they are using.

**Comment by AmarHadzic** [comment]
Hi Dr. Holdener, can I get this issue?

**Comment by kate-holdener** [comment]
@AmarHadzic All yours!

**Comment by AmarHadzic** [comment]
@kate-holdener for the ones that do not have an imported library, where should I put those?

**Comment by kate-holdener** [comment]
Resolved with pull request #115
